### ISSUE TITLE
Bug in test06

### ISSUE THREAD

**Issue by etosha** [norswap/rocketcrash#4]
I think that the line referenced below should be:

bar_caught = 1;

https://github.com/norswap/rocketcrash/blob/6e58dc5f102f33ebc4aec4c44b5f7a7b2aad7c7f/test.c#L163

It won't make any difference unless something goes wrong.

**Comment by norswap** [comment]
Good catch!
Fixed in https://github.com/norswap/rocketcrash/commit/707516747e627bf297809c94e41639f3e6e189f7
